/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import static Vistas.Colegio.alumnos;
import static Vistas.Colegio.materias;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Bossa
 */
public class Vista_Inscripcion extends javax.swing.JInternalFrame {

    /**
     * Creates new form Formulario_Inscripcion
     */
    public void rellenarBoxMaterias() {
        BoxMateria.removeAllItems();
        for (Materias objeto : materias) {
            BoxMateria.addItem(objeto);
        }
    }

    public void rellenarBoxAlumnos() {
        boxAlumno.removeAllItems();
        for (Alumno objeto : alumnos) {
            boxAlumno.addItem(objeto);
        }
    }

    public Vista_Inscripcion() {
        initComponents();
        rellenarBoxMaterias();
        rellenarBoxAlumnos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblMateria = new javax.swing.JLabel();
        lblAlumno = new javax.swing.JLabel();
        BoxMateria = new javax.swing.JComboBox<>();
        boxAlumno = new javax.swing.JComboBox<>();
        btninscribir = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        lblTitulo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblTitulo.setText("Formulario de Inscripcion");

        lblMateria.setText("Elija Una Materia");

        lblAlumno.setText("Elija Un Alumno");

        BoxMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxMateriaActionPerformed(evt);
            }
        });

        btninscribir.setText("Inscribir");
        btninscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninscribirActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btninscribir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir)
                .addGap(11, 11, 11))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMateria)
                            .addComponent(lblAlumno))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boxAlumno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BoxMateria, 0, 286, Short.MAX_VALUE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMateria)
                    .addComponent(BoxMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlumno)
                    .addComponent(boxAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btninscribir)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btninscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninscribirActionPerformed
        Materias materiaSeleccionada = (Materias) BoxMateria.getSelectedItem();
        Alumno alumnoSeleccionado = (Alumno) boxAlumno.getSelectedItem();
        try {
            if (materiaSeleccionada != null || alumnoSeleccionado != null) {
                if (alumnoSeleccionado.getMateriasInscripto().contains(materiaSeleccionada)) {
                    JOptionPane.showMessageDialog(this, "Este alumno ya esta inscripto en la materia seleccionada");
                } else {
                    alumnoSeleccionado.agregarMateria(materiaSeleccionada);
                    System.out.println(alumnoSeleccionado.cantidadMaterias());
                }
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Seleccione un alumno o materia.");
        }
    }//GEN-LAST:event_btninscribirActionPerformed

    private void BoxMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxMateriaActionPerformed

    }//GEN-LAST:event_BoxMateriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Materias> BoxMateria;
    private javax.swing.JComboBox<Alumno> boxAlumno;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btninscribir;
    private javax.swing.JLabel lblAlumno;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
